<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>adb</AssemblyName>
    <RootNamespace>FirmwareKit.Comm.ADB.Cli</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirmwareKit.Comm.ADB\FirmwareKit.Comm.ADB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="$(AssemblyName)" />
    <TrimmerRootAssembly Include="CommandLine" />
  </ItemGroup>

</Project>
